LIME-1019 - Updating common_lib version
govuk-one-login/ipv-cri-common-lambdas pull request #273
Opened 2024-02-15 14:47 UTC by ElliotMurphyGDS

### What changed
Updating Common_lib version to be latest. This is to pull in latest release which includes updates to the audit event timestamps so that they include milliseconds.

Additional Note:
will be reviewing other releases in between 1.4.3->1.5.6 to confirm no changes will be breaking in the jump in version

2024-02-15 16:13 UTC, surajkumar reviewed
Your tests are failing because `1.5.6` hasn't been published yet. 

Could you do a test with `1.5.5` to  make sure nothing is going to break unrelated to your changes?

2024-02-26 13:59 UTC, surajkumar requested changes

2024-02-26 13:59 UTC, surajkumar commented on infrastructure/lambda/template.yaml
> +      dev: "http://localhost:8085/callback"
What's the reasoning for changing the URL here?

2024-02-26 13:59 UTC, surajkumar commented on session/src/test/java/uk/gov/di/ipv/cri/common/api/service/SignedJWTBuilder.java
> +        } catch (JsonMappingException e) {
Instead of 2 distinct catch blocks, you can condense this into one i.e. `} catch (JsonMappingException | JsonProcessingException e) {`

2024-02-26 13:59 UTC, surajkumar commented on session/src/test/java/uk/gov/di/ipv/cri/common/api/service/SignedJWTBuilder.java
> +        } catch (JsonMappingException e) {
We should also be careful, that PII is not going to be exposed in this exception

2024-03-06 09:54 UTC, surajkumar approved these changes

2024-03-06 14:20 UTC, gds-jbentham approved these changes

2024-03-06 14:38 UTC, gds-jbentham approved these changes

2024-03-06 15:01 UTC, merlinc approved these changes

2024-03-06 15:19 UTC, merged